language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - wget -qO - https://dlang.org/d-keyring.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes dmd-bin dub dcd dfix dfmt dscanner

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false
  matrix:
  - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - Build and publish
    ORG_GRADLE_PROJECT_ideaVersion=2017.1

matrix:
  allow_failures:
  - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT

deploy:
  # deploy develop to the dev channel
  - provider: script
    env: [ ORG_GRADLE_PROJECT_publishChannels=dev, ORG_GRADLE_PROJECT_version=1.13-dev$TRAVIS_BUILD_NUMBER ]
    script: ./gradlew publishPlugin
    on:
      branch: develop
  # deploy master to eap channel
  - provider: script
    env: [ ORG_GRADLE_PROJECT_publishChannels=eap ]
    script: ./gradlew publishPlugin
    on:
      branch: master
  # deploy tags to stable channel
  - provider: script
    env: [ ORG_GRADLE_PROJECT_publishChannels=stable, ORG_GRADLE_PROJECT_version=$TRAVIS_TAG ]
    script: ./gradlew publishPlugin
    on:
      tags: true
