language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false
  - secure: Ix6Dg3nsYJgQfU1M9JWYKsdjk3KCzx1P73pdQxI9OKQszt0LJ3WIqFdX1FKPMRrSrqY32JNF2MV6oSrMa52mu7jtmZ2lw6BiInOZzdhsYzHw2NRueMClH6Qykj3YSIcnY+yW5nWs6XbTIwET/RtTzF1std5GhCX+KcbDMnnhQtc=
  - secure: mecxRWRy086Z+xeX4d2b8xi55IBKpNAQgfU8M2aTsfF4WTjXQYgdZT6QhuDSaFvOLoX3kgUfDY905ZBtWs/DS6Adx5fkLbJcLi+XsXlslfFwjA8cvlNhP8UyCCV10r3rYo2ro7sYCLJ3eMhbjH+LfaoPwQrtb36BLhjRWG4gx80=
  matrix:
  - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - ORG_GRADLE_PROJECT_ideaVersion=2016.3.5
  - ORG_GRADLE_PROJECT_ideaVersion=2016.3.4
  - ORG_GRADLE_PROJECT_ideaVersion=2016.3.1
  - ORG_GRADLE_PROJECT_ideaVersion=2016.3
matrix:
  allow_failures:
  - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
